name: Run Node Script

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  run-node-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install
        working-directory: ./generator

      - name: Run Node.js script
        run: node index.js
        working-directory: ./generator

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"

      - name: Commit changes
        run: |
          git add .
          git commit -m "Create or Update Data" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
